import Home from "./Home"
import Splash from "./Splash"
import Profile from "./Profile"
import Product from "./Product"
import JerseyDetail from "./JerseyDetail"
import Cart from "./Cart"
import Checkout from "./Checkout"
import EditProfile from "./EditProfile"
import ChangePassword from "./ChangePassword"
import History from "./History"
import Login from "./Login"
import Register1 from "./Register/Register1"
import Register2 from "./Register/Register2"
export { Home,Splash, Product, Profile, JerseyDetail, Cart, 
    Checkout, EditProfile, ChangePassword, History, Login, Register1, Register2}